services:
  php-apache:
    build: .
    ports:
      - "7080:80"
    volumes:
      - ./src:/var/www/html
    environment:
      PHP_EXTENSION_DIR: "/usr/local/lib/php/extensions/no-debug-non-zts-20180731"
    restart: always
